[workspace]
members = [
    ".",
    "src/ui",
    "src/orchestration"
]
resolver = "2"

[workspace.package]
name = "ark-os-production-ready"
version = "0.1.0"
edition = "2021"
authors = ["ARK-OS Contributors"]
license = "MIT OR Apache-2.0"

[workspace.dependencies]
# Core dependencies from all three repositories
anyhow = "1.0"
async-trait = "0.1"
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4.0", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
tokio = { version = "1.0", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
uuid = { version = "1.0", features = ["v4", "serde"] }

# Tauri dependencies (from rustecosys)
tauri = { version = "1.0", features = ["api-all"] }
tauri-build = { version = "1.0", features = [] }

# Additional dependencies found in source files
futures = "0.3"
once_cell = "1.0"
parking_lot = "0.12"
reqwest = { version = "0.11", features = ["json"] }

[package]
name = "ark-os-production-ready"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
# Workspace dependencies for main crate
anyhow.workspace = true
async-trait.workspace = true
chrono.workspace = true
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true

# Additional main crate dependencies
futures.workspace = true
once_cell.workspace = true

[[bin]]
name = "ark-os"
path = "src/main.rs"
