[package]
name = "wasm_host"
version = "0.2.0"
edition = "2021"

[dependencies]
anyhow = "1"
wasmtime = "22"
wasmtime-wasi = "22"
wat = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
base64 = "0.22"
hmac = "0.12"
sha2 = "0.10"
cap-std = "3"
