# SLO Policies for AgentAskit
# Reference: SLO-POLICY, OBS-DASH-ALERTS

apiVersion: slo/v1
kind: SLOPolicy
metadata:
  name: agentaskit-slos
  version: "1.0"

slos:
  # Latency SLOs
  - name: response-latency-p95
    description: "95th percentile response latency"
    target: 0.95
    window: 30d
    indicator:
      type: latency
      threshold: 50ms
      percentile: 95
    error_budget:
      monthly_budget: 0.05  # 5% of requests can exceed threshold
      burn_rate_windows:
        - 1h
        - 6h
        - 24h

  - name: response-latency-p99
    description: "99th percentile response latency"
    target: 0.99
    window: 30d
    indicator:
      type: latency
      threshold: 500ms
      percentile: 99

  # Availability SLO
  - name: service-availability
    description: "Service uptime availability"
    target: 0.9999  # 99.99% uptime
    window: 30d
    indicator:
      type: availability
      success_rate: true
    error_budget:
      monthly_budget: 0.0001
      max_downtime_minutes: 4.32  # per month

  # Error Rate SLO
  - name: error-rate
    description: "HTTP 5xx error rate"
    target: 0.999  # 99.9% success
    window: 30d
    indicator:
      type: error_rate
      threshold: 0.001
    error_budget:
      monthly_budget: 0.001
      burn_rate_windows:
        - 5m
        - 1h
        - 6h

  # Throughput SLO
  - name: throughput-tasks
    description: "Task processing throughput"
    target: 0.95
    window: 30d
    indicator:
      type: throughput
      minimum_rate: 10000  # tasks per second
    
  - name: throughput-messages
    description: "Message processing throughput"
    target: 0.95
    window: 30d
    indicator:
      type: throughput
      minimum_rate: 100000  # messages per second

  # Startup Latency SLO
  - name: cold-start-latency
    description: "Agent cold start time"
    target: 0.95
    window: 30d
    indicator:
      type: latency
      threshold: 100ms
      percentile: 95

alerts:
  # Alert when approaching error budget exhaustion
  burn_rate_thresholds:
    - window: 1h
      threshold: 14.4  # Will exhaust budget in ~2 days
      severity: warning
    - window: 6h
      threshold: 6.0   # Will exhaust budget in ~5 days
      severity: warning
    - window: 24h
      threshold: 3.0   # Will exhaust budget in ~10 days
      severity: info

  # Page when budget is critically low
  budget_remaining_thresholds:
    - remaining: 0.25
      severity: warning
    - remaining: 0.10
      severity: critical
    - remaining: 0.0
      severity: page

reporting:
  dashboards:
    - path: dashboards/slo-overview.json
    - path: dashboards/error-budget.json
  weekly_review: true
  monthly_review: true
