
[package]
name = "flex-core"
version = "0.3.0"
edition = "2021"
build = "build.rs"

[dependencies]
tokio = { version = "1", features = ["rt-multi-thread","macros","net","io-util","time","process"] }
anyhow = "1"
capnp = "0.19"
capnp-rpc = "0.19"
sha2 = "0.10"
hex = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
walkdir = "2"

[build-dependencies]
capnpc = "0.19"

[[bin]]
name = "flex-core"
path = "src/main.rs"

[[bin]]
name = "flex-client"
path = "src/client.rs"
