
[package]
name = "flex-core"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net", "io-util", "time"] }
anyhow = "1"
capnp = "0.19"
capnp-rpc = "0.19"
