name: SCA (Dependency Scan)

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  sca:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Dependency scan placeholder
        run: |
          echo "SCA stub - integrate your preferred scanner (e.g., Trivy, osv-scanner, pip-audit)"
