name: TODO ⇄ Issues Sync
on:
  push:
    paths: [ 'agentaskit-production/.todo' ]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Sync stub
        run: echo "Sync .todo with issues (stub)"